require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '10.0'

target 'Mobile' do
  config = use_native_modules!
  puts config
  use_react_native!(:path => config[:reactNativePath])
  pod 'React-jsi', :path => '../../../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  permissions_path = '../../../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  post_install do |installer|

    nx_post_install(installer)
  end
end
