require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '11.0'

target 'Mobile' do
  config = use_native_modules!
  puts config
  use_react_native!(:path => config[:reactNativePath])
  pod 'React-jsi', :path => '../../../node_modules/react-native/ReactCommon/jsi', 
  :modular_headers => true
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end


    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_11_0/' Pods/RCT-Folly/folly/portability/Time.h`
    nx_post_install(installer)
  end
end
